from dataclasses import dataclass
from typing import List


@dataclass(frozen=True)
class Provider:
    name: str
    domain: str
    auth: str
    env_vars: List[str]
    free_tier: bool


PROVIDERS: List[Provider] = [
    Provider("OpenSky Network", "aviation", "oauth/token", ["OPENSKY_CLIENT_ID", "OPENSKY_CLIENT_SECRET"], True),
    Provider("ADS-B Exchange", "aviation", "api_key", ["ADSB_EXCHANGE_API_KEY"], False),
    Provider("FlightAware Firehose", "aviation", "api_key", ["FLIGHTAWARE_API_KEY"], False),
    Provider("Flightradar24", "aviation", "api_key", ["FLIGHTRADAR24_API_KEY"], False),
    Provider("RadarBox", "aviation", "api_key", ["RADARBOX_API_KEY"], False),
    Provider("Aviationstack", "aviation", "api_key", ["AVIATIONSTACK_API_KEY"], True),
    Provider("AeroDataBox", "aviation", "api_key", ["AERODATABOX_API_KEY"], False),
    Provider("Aviation Edge", "aviation", "api_key", ["AVIATION_EDGE_API_KEY"], False),
    Provider("FlightStats", "aviation", "app_id/app_key", ["FLIGHTSTATS_APP_ID", "FLIGHTSTATS_APP_KEY"], False),
    Provider("FlightLabs", "aviation", "api_key", ["FLIGHTLABS_API_KEY"], True),
    Provider("Eurocontrol B2B", "aviation", "oauth/cert", ["EUROCONTROL_CLIENT_ID", "EUROCONTROL_CLIENT_SECRET"], False),
    Provider("FAA SWIM", "aviation", "cert+credentials", ["FAA_SWIM_USERNAME", "FAA_SWIM_PASSWORD"], False),
    Provider("MarineTraffic", "maritime", "api_key", ["MARINETRAFFIC_API_KEY"], False),
    Provider("VesselFinder", "maritime", "api_key", ["VESSELFINDER_API_KEY"], False),
    Provider("AISStream", "maritime", "api_key", ["AISSTREAM_API_KEY"], True),
    Provider("FleetMon", "maritime", "api_key", ["FLEETMON_API_KEY"], False),
    Provider("Datalastic", "maritime", "api_key", ["DATALASTIC_API_KEY"], False),
    Provider("AISHub", "maritime", "api_key", ["AISHUB_API_KEY"], True),
    Provider("Global Fishing Watch", "maritime", "token", ["GFW_TOKEN"], True),
    Provider("Spire Maritime", "maritime", "api_key", ["SPIRE_API_KEY"], False),
    Provider("ORBCOMM", "maritime", "api_key", ["ORBCOMM_API_KEY"], False),
    Provider("exactEarth", "maritime", "api_key", ["EXACTEARTH_API_KEY"], False),
    Provider("Space-Track", "satellite", "username/password", ["SPACETRACK_USERNAME", "SPACETRACK_PASSWORD"], True),
    Provider("CelesTrak", "satellite", "none", [], True),
    Provider("N2YO", "satellite", "api_key", ["N2YO_API_KEY"], True),
    Provider("SatNOGS", "satellite", "token(optional)", ["SATNOGS_API_TOKEN"], True),
    Provider("RocketLaunch.Live", "satellite", "api_key", ["ROCKETLAUNCHLIVE_API_KEY"], True),
    Provider("Planet", "imagery", "api_key", ["PLANET_API_KEY"], False),
    Provider("Sentinel Hub", "imagery", "oauth", ["SENTINELHUB_CLIENT_ID", "SENTINELHUB_CLIENT_SECRET"], True),
    Provider("NASA EarthData", "imagery", "earthdata_login", ["EARTHDATA_USERNAME", "EARTHDATA_PASSWORD"], True),
    Provider("ESA EO", "imagery", "oauth", ["ESA_EO_CLIENT_ID", "ESA_EO_CLIENT_SECRET"], True),
    Provider("Maxar SecureWatch", "imagery", "api_key", ["MAXAR_API_KEY"], False),
    Provider("BlackSky", "imagery", "api_key", ["BLACKSKY_API_KEY"], False),
    Provider("Capella Space", "imagery", "api_key", ["CAPELLA_API_KEY"], False),
    Provider("HawkEye 360", "rf", "api_key", ["HAWKEYE360_API_KEY"], False),
    Provider("OpenStreetMap", "geospatial", "none", [], True),
    Provider("Overpass", "geospatial", "none", [], True),
    Provider("Mapbox", "geospatial", "token", ["MAPBOX_ACCESS_TOKEN"], True),
    Provider("Google Maps Platform", "geospatial", "api_key", ["GOOGLE_MAPS_API_KEY"], False),
    Provider("HERE Maps", "geospatial", "api_key", ["HERE_API_KEY"], False),
    Provider("OpenCage", "geospatial", "api_key", ["OPENCAGE_API_KEY"], True),
    Provider("Nominatim", "geospatial", "none", [], True),
    Provider("GeoNames", "geospatial", "username", ["GEONAMES_USERNAME"], True),
    Provider("MapTiler", "geospatial", "api_key", ["MAPTILER_API_KEY"], True),
    Provider("GDELT", "news", "none", [], True),
    Provider("Event Registry", "news", "api_key", ["EVENTREGISTRY_API_KEY"], False),
    Provider("NewsAPI", "news", "api_key", ["NEWSAPI_KEY"], True),
    Provider("Mediastack", "news", "api_key", ["MEDIASTACK_API_KEY"], True),
    Provider("AYLIEN", "news", "app_id/app_key", ["AYLIEN_APP_ID", "AYLIEN_APP_KEY"], False),
    Provider("Bing News Search", "news", "api_key", ["BING_NEWS_API_KEY"], False),
    Provider("ACLED", "conflict", "api_key", ["ACLED_API_KEY"], True),
    Provider("UCDP", "conflict", "download", [], True),
    Provider("Global Terrorism Database", "conflict", "download", [], True),
    Provider("ReliefWeb", "conflict", "none", [], True),
    Provider("X/Twitter API", "social", "oauth2", ["X_API_KEY", "X_API_SECRET", "X_BEARER_TOKEN"], False),
    Provider("Reddit API", "social", "oauth2", ["REDDIT_CLIENT_ID", "REDDIT_CLIENT_SECRET"], True),
    Provider("YouTube Data API", "social", "api_key", ["YOUTUBE_API_KEY"], True),
    Provider("Mastodon API", "social", "token(optional)", ["MASTODON_ACCESS_TOKEN"], True),
    Provider("Telegram Bot API", "social", "bot_token", ["TELEGRAM_BOT_TOKEN"], True),
    Provider("Shodan", "cyber", "api_key", ["SHODAN_API_KEY"], False),
    Provider("Censys", "cyber", "api_id/api_secret", ["CENSYS_API_ID", "CENSYS_API_SECRET"], True),
    Provider("BinaryEdge", "cyber", "api_key", ["BINARYEDGE_API_KEY"], False),
    Provider("GreyNoise", "cyber", "api_key", ["GREYNOISE_API_KEY"], False),
    Provider("LeakIX", "cyber", "api_key", ["LEAKIX_API_KEY"], True),
    Provider("Netlas", "cyber", "api_key", ["NETLAS_API_KEY"], True),
    Provider("ZoomEye", "cyber", "api_key", ["ZOOMEYE_API_KEY"], False),
    Provider("Have I Been Pwned", "identity", "api_key", ["HIBP_API_KEY"], True),
    Provider("Intelligence X", "identity", "api_key", ["INTELX_API_KEY"], False),
    Provider("DeHashed", "identity", "api_key", ["DEHASHED_API_KEY"], False),
    Provider("People Data Labs", "identity", "api_key", ["PDL_API_KEY"], False),
    Provider("Hunter.io", "identity", "api_key", ["HUNTER_API_KEY"], True),
    Provider("Clearbit", "identity", "api_key", ["CLEARBIT_API_KEY"], False),
    Provider("OpenCorporates", "financial", "token(optional)", ["OPENCORPORATES_API_TOKEN"], True),
    Provider("OpenSanctions", "financial", "none", [], True),
    Provider("OFAC Sanctions", "financial", "none", [], True),
    Provider("OCCRP Aleph", "financial", "api_key", ["ALEPH_API_KEY"], True),
    Provider("UK Companies House", "financial", "api_key", ["COMPANIES_HOUSE_API_KEY"], True),
    Provider("NOAA", "weather", "api_key(optional)", ["NOAA_API_KEY"], True),
    Provider("OpenWeather", "weather", "api_key", ["OPENWEATHER_API_KEY"], True),
    Provider("ECMWF", "weather", "key/url/email", ["ECMWF_URL", "ECMWF_KEY", "ECMWF_EMAIL"], True),
    Provider("Meteostat", "weather", "rapidapi_key(optional)", ["RAPIDAPI_KEY"], True),
    Provider("Stormglass", "weather", "api_key", ["STORMGLASS_API_KEY"], True),
    Provider("USGS Earthquake", "disaster", "none", [], True),
    Provider("GDACS", "disaster", "none", [], True),
    Provider("NASA FIRMS", "disaster", "map_key", ["FIRMS_MAP_KEY"], True),
    Provider("EMSC", "disaster", "none", [], True),
    Provider("Copernicus EMS", "disaster", "none", [], True),
    Provider("OpenCellID", "telecom", "api_key", ["OPENCELLID_API_KEY"], True),
    Provider("CellMapper", "telecom", "none", [], True),
    Provider("WiGLE", "telecom", "api_name/token", ["WIGLE_API_NAME", "WIGLE_API_TOKEN"], True),
    Provider("GPSJam", "gnss", "none", [], True),
    Provider("GNSS Service Centre", "gnss", "none", [], True),
    Provider("STRIKE3", "gnss", "api_key", ["STRIKE3_API_KEY"], False),
    Provider("NetBlocks", "internet", "none", [], True),
    Provider("Cloudflare Radar", "internet", "none", [], True),
    Provider("RIPEstat", "internet", "none", [], True),
    Provider("BGPStream", "internet", "none", [], True),
    Provider("OpenRailwayMap", "rail", "none", [], True),
    Provider("Transitland", "rail", "api_key", ["TRANSITLAND_API_KEY"], True),
    Provider("OpenMobilityData", "rail", "none", [], True),
    Provider("geOps Mobility", "rail", "api_key", ["GEOPS_API_KEY"], False),
    Provider("OSINT Industries", "identity", "api_key", ["OSINT_INDUSTRIES_API_KEY"], False),
    Provider("Searchbug", "identity", "api_key", ["SEARCHBUG_API_KEY"], False),
    Provider("Interpol Notices", "financial", "none", [], True),
    Provider("FBI Wanted API", "financial", "none", [], True),
]


def required_env_vars() -> List[str]:
    envs = sorted({env for provider in PROVIDERS for env in provider.env_vars})
    return envs
